## Cleaning data with Python.

In [1]:
# Import packages
import pandas as pd

# Import dataset
auto = pd.read_csv("autodata.csv")

# Display auto
auto

  Manufacturer        Model  Drive EngineType  Cylinders  Liters    MPG
0         Audi           A4    All        Gas        4.0     2.0   24.0
1          BMW       328 Ci   Rear        Gas        6.0     3.6  210.0
2      Bentley  Continental   Rear        Gas        NaN     NaN   21.0
3    Chevrolet       Malibu  Front        Gas        6.0     3.6   18.0
4         Ford      Mustang   Rear        Gas        6.0     3.7    NaN
5  Rolls-Royce        Ghost   Rear        Gas       12.0     6.6   12.0
6    Chevrolet       Malibu  Front        Gas        6.0     3.6   18.0

In [2]:
# Which rows have missing values?
auto.isnull()

   Manufacturer  Model  Drive  EngineType  Cylinders  Liters    MPG
0         False  False  False       False      False   False  False
1         False  False  False       False      False   False  False
2         False  False  False       False       True    True  False
3         False  False  False       False      False   False  False
4         False  False  False       False      False   False   True
5         False  False  False       False      False   False  False
6         False  False  False       False      False   False  False

In [3]:
# Count the colm with missing values for each feature
auto.isnull().sum()

Manufacturer    0
Model           0
Drive           0
EngineType      0
Cylinders       1
Liters          1
MPG             1
dtype: int64

In [4]:
# Remove duplicates from dataset
auto.drop_duplicates(inplace=True)
auto

  Manufacturer        Model  Drive EngineType  Cylinders  Liters    MPG
0         Audi           A4    All        Gas        4.0     2.0   24.0
1          BMW       328 Ci   Rear        Gas        6.0     3.6  210.0
2      Bentley  Continental   Rear        Gas        NaN     NaN   21.0
3    Chevrolet       Malibu  Front        Gas        6.0     3.6   18.0
4         Ford      Mustang   Rear        Gas        6.0     3.7    NaN
5  Rolls-Royce        Ghost   Rear        Gas       12.0     6.6   12.0

In [5]:
# Remove rows with missing values for both Cylinders and Liters
auto.dropna(subset=['Cylinders', 'Liters'], how='all', inplace=True)
auto

  Manufacturer    Model  Drive EngineType  Cylinders  Liters    MPG
0         Audi       A4    All        Gas        4.0     2.0   24.0
1          BMW   328 Ci   Rear        Gas        6.0     3.6  210.0
3    Chevrolet   Malibu  Front        Gas        6.0     3.6   18.0
4         Ford  Mustang   Rear        Gas        6.0     3.7    NaN
5  Rolls-Royce    Ghost   Rear        Gas       12.0     6.6   12.0

In [6]:
# Remove features with missing values in a given row
auto.dropna(axis=1, subset=[3])
auto

  Manufacturer    Model  Drive EngineType  Cylinders  Liters    MPG
0         Audi       A4    All        Gas        4.0     2.0   24.0
1          BMW   328 Ci   Rear        Gas        6.0     3.6  210.0
3    Chevrolet   Malibu  Front        Gas        6.0     3.6   18.0
4         Ford  Mustang   Rear        Gas        6.0     3.7    NaN
5  Rolls-Royce    Ghost   Rear        Gas       12.0     6.6   12.0

In [7]:
auto.replace(to_replace=210.0, value=21, inplace=True)
auto

  Manufacturer    Model  Drive EngineType  Cylinders  Liters   MPG
0         Audi       A4    All        Gas        4.0     2.0  24.0
1          BMW   328 Ci   Rear        Gas        6.0     3.6  21.0
3    Chevrolet   Malibu  Front        Gas        6.0     3.6  18.0
4         Ford  Mustang   Rear        Gas        6.0     3.7   NaN
5  Rolls-Royce    Ghost   Rear        Gas       12.0     6.6  12.0

In [8]:
# Compute mean values of numeric features
mean = auto.mean(numeric_only=True)
auto.fillna(value=mean, inplace=True)
auto

  Manufacturer    Model  Drive EngineType  Cylinders  Liters    MPG
0         Audi       A4    All        Gas        4.0     2.0  24.00
1          BMW   328 Ci   Rear        Gas        6.0     3.6  21.00
3    Chevrolet   Malibu  Front        Gas        6.0     3.6  18.00
4         Ford  Mustang   Rear        Gas        6.0     3.7  18.75
5  Rolls-Royce    Ghost   Rear        Gas       12.0     6.6  12.00

## challenge activity 5.4.2: Cleaning data using pandas.

## This dataset contains information on lifestyle measures such as the amount of sunshine, pollution, and happiness levels for 44 major cities around the world.

* **Drop instances with duplicate values of sunshine_hours from the dataset.**
* 
**The code contains all imports, loads the dataset, and displays healthyClean.info().**

In [17]:
# Import packages and functions
import pandas as pd

# Load the dataset
healthy = pd.read_csv('healthy_example.csv')


# Remove instances with duplicate values of sunshine_hours 
healthy = healthy.drop_duplicates(subset=['sunshine_hours'])  

healthy

,cost_bottled_water,annual_hours_worked,sunshine_hours,number_takeout_places
0,£1.92,1434.0,1858.0,1048.0
1,£1.48,1712.0,2636.0,1103.0
2,£1.94,1501.0,1884.0,1008.0
3,£1.72,1452.0,1821.0,598.0
4,£2.19,1380.0,1630.0,523.0
5,£1.60,1540.0,1662.0,309.0
6,£0.78,1644.0,2769.0,539.0
7,£1.55,1386.0,1626.0,1729.0
8,£1.19,1686.0,2591.0,2344.0
9,NaN,1670.0,1938.0,788.0
10,£1.57,1712.0,2363.0,813.0
11,£0.26,NaN,2671.0,261.0
12,£0.22,NaN,2624.0,1796.0
13,£0.57,NaN,2525.0,1435.0
14,£1.09,1670.0,2066.0,1656.0
16,£0.21,NaN,2983.0,833.0
19,£2.62,1557.0,NaN,444.0
20,£1.63,1898.0,3311.0,420.0
21,£0.15,1832.0,2218.0,934.0
22,£0.16,NaN,3542.0,250.0
23,£0.57,NaN,1405.0,717.0
24,£1.52,1779.0,3254.0,1439.0
25,£0.15,NaN,2584.0,1183.0
26,£1.39,1779.0,2634.0,588.0
27,£1.40,1772.0,1453.0,659.0
28,£0.76,1644.0,1877.0,5802.0
29,£1.20,1779.0,2508.0,1320.0
30,£0.75,NaN,1836.0,1257.0
31,£0.29,NaN,1776.0,346.0
32,£2.11,1583.0,1546.0,988.0
33,£1.60,1779.0,3062.0,1031.0
35,£0.44,NaN,2003.0,3355.0
36,£3.20,1557.0,1566.0,NaN
37,£1.16,1538.0,1633.0,6417.0
38,£0.59,NaN,3124.0,492.0
39,£1.15,1718.0,1915.0,2396.0
40,£1.45,1779.0,2528.0,744.0
41,£1.32,1779.0,2535.0,3081.0
42,£0.41,1965.0,1901.0,3206.0
43,£0.45,2137.0,2555.0,1313.0

# 2

**This dataset contains information on lifestyle measures such as the amount of sunshine, pollution, and happiness levels for 44 major cities around the world.**

* **Drop features with missing values of instance 11 from the dataset.**

**The code contains all imports, loads the dataset, and displays lifestyleClean.info().**

In [26]:
# Import packages and functions
import pandas as pd

# Load the dataset
lifestyleClean = pd.read_csv('healthy_example.csv')

# Remove features with missing values of 11
lifestyleClean = lifestyleClean.dropna()

lifestyleClean.info()

<class 'pandas.DataFrame'>
Index: 30 entries, 0 to 43
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   cost_bottled_water     30 non-null     str
 1   annual_hours_worked    30 non-null     float64
 2   sunshine_hours         30 non-null     float64
 3   number_takeout_places  30 non-null     float64
dtypes: float64(3), str(1)
memory usage: 1.2 KB

# 3) **This dataset contains information on lifestyle measures such as the amount of sunshine, pollution, and happiness levels for 44 major cities around the world.**

* **Calculate and print the mean value of sunshine_hours.**

* **Replace the missing values of sunshine_hours in place with the mean of sunshine_hours.**

**The code contains all imports, loads the dataset, and displays healthy['sunshine_hours'].**

In [ ]:
# Import packages and functions
import pandas as pd

# Load the dataset
healthy = pd.read_csv('healthy_example.csv')

# Calculate the mean values of the features
healthyMean = # Your code goes here
print('Mean:', healthyMean['sunshine_hours'], '\n')

# Replace missing values of sunshine_hours in place with the mean of sunshine_hours
# Your code goes here

print(healthy['sunshine_hours'])